sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
#  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get install -y libqt4-dev libqwt5-qt4-dev

script:
  - qmake qwt5.pro
  - make
#EOF
